import type {
  BookRecord,
  LoanSlip,
  Reader,
  SupplierContract,
  SystemUser,
} from '../types'

export const supplierContracts: SupplierContract[] = [
  {
    id: 'c1',
    code: 'HD-2026-001',
    title: 'Cung cấp sách khoa học 2026',
    supplierName: 'NXB Kim Đồng',
    type: 'Mua sách',
    value: 250000000,
    signedDate: '2026-01-10',
    expiryDate: '2026-12-31',
    status: 'active',
  },
  {
    id: 'c2',
    code: 'HD-2025-045',
    title: 'Bảo trì hệ thống máy tính thư viện',
    supplierName: 'Công ty TNHH FPT Services',
    type: 'Dịch vụ',
    value: 80000000,
    signedDate: '2025-03-01',
    expiryDate: '2026-10-05',
    status: 'expiring',
  },
  {
    id: 'c3',
    code: 'HD-2024-112',
    title: 'Mua sắm bàn ghế phòng đọc',
    supplierName: 'Nội thất Hòa Phát',
    type: 'Thiết bị',
    value: 120000000,
    signedDate: '2024-05-20',
    expiryDate: '2025-05-20',
    status: 'expired',
  },
  {
    id: 'c4',
    code: 'HD-2023-078',
    title: 'Cung cấp phần mềm quản lý thư viện',
    supplierName: 'Công ty CP Giải pháp VNIT',
    type: 'Phần mềm',
    value: 60000000,
    signedDate: '2023-06-01',
    expiryDate: '2024-06-01',
    status: 'liquidated',
  },
]

export const loanSlips: LoanSlip[] = [
  {
    id: 'l1',
    code: 'PM-000231',
    readerName: 'Nguyễn Văn An',
    bookTitle: 'Đắc Nhân Tâm',
    borrowDate: '2026-09-10',
    dueDate: '2026-09-24',
    returnDate: null,
    status: 'borrowing',
  },
  {
    id: 'l2',
    code: 'PM-000230',
    readerName: 'Trần Thị Bích',
    bookTitle: 'Nhà Giả Kim',
    borrowDate: '2026-09-01',
    dueDate: '2026-09-15',
    returnDate: null,
    status: 'overdue',
  },
  {
    id: 'l3',
    code: 'PM-000229',
    readerName: 'Lê Minh Châu',
    bookTitle: 'Sapiens: Lược Sử Loài Người',
    borrowDate: '2026-08-20',
    dueDate: '2026-09-03',
    returnDate: '2026-09-02',
    status: 'returned',
  },
  {
    id: 'l4',
    code: 'PM-000228',
    readerName: 'Phạm Quốc Đạt',
    bookTitle: 'Clean Code',
    borrowDate: '2026-09-18',
    dueDate: '2026-10-02',
    returnDate: null,
    status: 'borrowing',
  },
]

export const readers: Reader[] = [
  {
    id: 'r1',
    code: 'DG-1001',
    fullName: 'Nguyễn Văn An',
    email: 'an.nguyen@email.com',
    phone: '0901 234 567',
    cardExpiry: '2027-03-15',
    borrowingCount: 1,
    status: 'active',
  },
  {
    id: 'r2',
    code: 'DG-1002',
    fullName: 'Trần Thị Bích',
    email: 'bich.tran@email.com',
    phone: '0912 345 678',
    cardExpiry: '2026-11-01',
    borrowingCount: 1,
    status: 'active',
  },
  {
    id: 'r3',
    code: 'DG-0987',
    fullName: 'Hoàng Văn Cường',
    email: 'cuong.hoang@email.com',
    phone: '0987 654 321',
    cardExpiry: '2025-12-01',
    borrowingCount: 0,
    status: 'expired',
  },
  {
    id: 'r4',
    code: 'DG-1050',
    fullName: 'Đỗ Thị Duyên',
    email: 'duyen.do@email.com',
    phone: '0977 111 222',
    cardExpiry: '2026-06-30',
    borrowingCount: 0,
    status: 'locked',
  },
]

export const books: BookRecord[] = [
  {
    id: 'b1',
    code: 'S-00231',
    title: 'Đắc Nhân Tâm',
    author: 'Dale Carnegie',
    publisher: 'NXB Tổng hợp TP.HCM',
    category: 'Kỹ năng sống',
    quantity: 10,
    available: 9,
    status: 'available',
  },
  {
    id: 'b2',
    code: 'S-00198',
    title: 'Nhà Giả Kim',
    author: 'Paulo Coelho',
    publisher: 'NXB Văn học',
    category: 'Văn học',
    quantity: 6,
    available: 5,
    status: 'available',
  },
  {
    id: 'b3',
    code: 'S-00305',
    title: 'Clean Code',
    author: 'Robert C. Martin',
    publisher: 'Prentice Hall',
    category: 'Công nghệ',
    quantity: 4,
    available: 0,
    status: 'borrowed_out',
  },
  {
    id: 'b4',
    code: 'S-00042',
    title: 'Giáo trình Toán cao cấp A1 (cũ)',
    author: 'Bộ GD&ĐT',
    publisher: 'NXB Giáo dục',
    category: 'Giáo trình',
    quantity: 0,
    available: 0,
    status: 'liquidated',
  },
]

export const systemUsers: SystemUser[] = [
  {
    id: 'u1',
    fullName: 'Phạm Thị Hoa',
    email: 'hoa.pham@thuvien.edu.vn',
    role: 'admin',
    active: true,
  },
  {
    id: 'u2',
    fullName: 'Nguyễn Văn Long',
    email: 'long.nguyen@thuvien.edu.vn',
    role: 'librarian',
    active: true,
  },
  {
    id: 'u3',
    fullName: 'Vũ Thị Mai',
    email: 'mai.vu@thuvien.edu.vn',
    role: 'librarian',
    active: false,
  },
]
